//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public long ID { get; set; }
        public string countryID { get; set; }
        public string stateID { get; set; }
        public string lgaID { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string zip { get; set; }
        public string telephone1 { get; set; }
        public string telephone2 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
        public string xsync { get; set; }
    }
}
