//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee_listx
    {
        public long xid { get; set; }
        public string item { get; set; }
        public string item_code { get; set; }
        public string qt_code { get; set; }
        public string xdesc { get; set; }
        public Nullable<int> init_amt { get; set; }
        public Nullable<int> tech_amt { get; set; }
        public Nullable<int> switch_party { get; set; }
        public Nullable<int> t_party { get; set; }
        public string xcategory { get; set; }
        public string xlogstaff { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
