//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee_details
    {
        public long xid { get; set; }
        public string fee_listID { get; set; }
        public string twalletID { get; set; }
        public string xqty { get; set; }
        public string xused { get; set; }
        public string init_amt { get; set; }
        public string tech_amt { get; set; }
        public string tot_amt { get; set; }
        public string xlogstaff { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
