//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class hwallet
    {
        public long xid { get; set; }
        public string transID { get; set; }
        public string fee_detailsID { get; set; }
        public string product_title { get; set; }
        public string used_status { get; set; }
        public string xreg_date { get; set; }
        public string used_date { get; set; }
    }
}
