//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterSwitchPostField
    {
        public long xid { get; set; }
        public string product_id { get; set; }
        public string amount { get; set; }
        public string isw_conv_fee { get; set; }
        public string currency { get; set; }
        public string site_redirect_url { get; set; }
        public string txn_ref { get; set; }
        public string hash { get; set; }
        public string mackey { get; set; }
        public string pay_item_id { get; set; }
        public string site_name { get; set; }
        public string cust_id { get; set; }
        public string cust_id_desc { get; set; }
        public string cust_name { get; set; }
        public string resp_desc { get; set; }
        public string pay_item_name { get; set; }
        public Nullable<System.DateTime> local_date_time { get; set; }
        public string TransactionDate { get; set; }
        public string MerchantReference { get; set; }
        public string trans_status { get; set; }
        public string pay_ref { get; set; }
        public string ret_ref { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
