//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ba2xai_xpay_backupEntities : DbContext
    {
        public ba2xai_xpay_backupEntities()
            : base("name=ba2xai_xpay_backupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<admin_lg> admin_lg { get; set; }
        public virtual DbSet<applicant> applicants { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<fee_details> fee_details { get; set; }
        public virtual DbSet<fee_list> fee_list { get; set; }
        public virtual DbSet<hwallet> hwallets { get; set; }
        public virtual DbSet<InterSwitchPostField> InterSwitchPostFields { get; set; }
        public virtual DbSet<lga> lgas { get; set; }
        public virtual DbSet<p_ratio> p_ratio { get; set; }
        public virtual DbSet<pwallet> pwallets { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<scard> scards { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<twallet> twallets { get; set; }
        public virtual DbSet<xadmin> xadmins { get; set; }
        public virtual DbSet<xagent> xagents { get; set; }
        public virtual DbSet<xbanker> xbankers { get; set; }
        public virtual DbSet<xmember> xmembers { get; set; }
        public virtual DbSet<xpartner> xpartners { get; set; }
        public virtual DbSet<fee_listx> fee_listx { get; set; }
        public virtual DbSet<InterSwitchPostFields2> InterSwitchPostFields2 { get; set; }
    }
}
