//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_ratio
    {
        public long xid { get; set; }
        public string xpartnerID { get; set; }
        public string p_type { get; set; }
        public string xratio { get; set; }
        public string r_type { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
