//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwallet
    {
        public long xid { get; set; }
        public string xmembertype { get; set; }
        public string xmemberID { get; set; }
        public string xemail { get; set; }
        public string xmobile { get; set; }
        public string xpass { get; set; }
        public string reg_date { get; set; }
    }
}
