//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration2
    {
        public long xid { get; set; }
        public string AccrediationType { get; set; }
        public string Sys_ID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string xpassword { get; set; }
        public string DateOfBrith { get; set; }
        public string IncorporatedDate { get; set; }
        public string Nationality { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonPhone { get; set; }
        public string CompanyWebsite { get; set; }
        public string Certificate { get; set; }
        public string Introduction { get; set; }
        public string Principal { get; set; }
        public string xreg_date { get; set; }
        public string xstatus { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
