//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class subagent
    {
        public long xid { get; set; }
        public string RegistrationID { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Email { get; set; }
        public string xpassword { get; set; }
        public string Telephone { get; set; }
        public string AssignID { get; set; }
        public string Sys_ID { get; set; }
        public string Address { get; set; }
        public string AgentPassport { get; set; }
        public string xreg_date { get; set; }
        public string xstatus { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
