//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class twallet
    {
        public long xid { get; set; }
        public string transID { get; set; }
        public string xmemberID { get; set; }
        public string xmembertype { get; set; }
        public string xpay_status { get; set; }
        public string xgt { get; set; }
        public string ref_no { get; set; }
        public string xbankerID { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
        public string applicantID { get; set; }
    }
}
