//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class xpartner
    {
        public long xid { get; set; }
        public string xname { get; set; }
        public string cname { get; set; }
        public string nationality { get; set; }
        public string addressID { get; set; }
        public string sys_ID { get; set; }
        public string xpassword { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
        public string xsync { get; set; }
    }
}
