//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_lg
    {
        public int id { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> act_date { get; set; }
        public string DocumentId { get; set; }
        public string Operation { get; set; }
        public string module { get; set; }
        public string status { get; set; }
        public string old_title { get; set; }
        public string new_title { get; set; }
        public string old_class { get; set; }
        public string new_class { get; set; }
        public string old_applicantname { get; set; }
        public string new_applicantname { get; set; }
    }
}
