//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_lg
    {
        public long ID { get; set; }
        public string adminID { get; set; }
        public string ip_addy { get; set; }
        public string remote_host { get; set; }
        public string remote_user { get; set; }
        public string server_name { get; set; }
        public string server_url { get; set; }
        public string log_date { get; set; }
        public string log_time { get; set; }
    }
}
