//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Mail
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date_Sent { get; set; }
        public string Agent_Code { get; set; }
        public Nullable<bool> Status { get; set; }
        public string pt_id { get; set; }
        public string reg_number { get; set; }
        public string Recordal_id { get; set; }
    }
}
