//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_FileUpload
    {
        public int id { get; set; }
        public string agent_code { get; set; }
        public string old_file { get; set; }
        public string new_file { get; set; }
        public Nullable<System.DateTime> Date_Uploaded { get; set; }
        public string Status { get; set; }
        public string pt_id { get; set; }
    }
}
