//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public long xID { get; set; }
        public string applicant_name { get; set; }
        public string applicant_address { get; set; }
        public string prev_renewal_date { get; set; }
        public string certificate_number { get; set; }
        public string nice_class { get; set; }
        public string nice_class_desc { get; set; }
        public string trademark { get; set; }
        public string logo_descID { get; set; }
        public string assignor_name { get; set; }
        public string assignor_address { get; set; }
        public string assignee_name { get; set; }
        public string assignee_address { get; set; }
        public string agreement_date { get; set; }
        public string agent_name { get; set; }
        public string agent_code { get; set; }
        public string agent_mail { get; set; }
        public string assignment_pwalletID { get; set; }
        public string logo_pic { get; set; }
        public string poa_doc { get; set; }
        public string deed_doc { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
    }
}
