//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class cert_info
    {
        public long xID { get; set; }
        public string pub_date { get; set; }
        public string pub_details { get; set; }
        public string cert_doc { get; set; }
        public string pub_doc { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string xvisible { get; set; }
    }
}
