//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ba2xai_cldxEntities : DbContext
    {
        public ba2xai_cldxEntities()
            : base("name=ba2xai_cldxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity_lg> activity_lg { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<address_service> address_service { get; set; }
        //public virtual DbSet<admin_lg> admin_lg { get; set; }
        public virtual DbSet<Admin_Mail> Admin_Mail { get; set; }
        public virtual DbSet<Agent_FileUpload> Agent_FileUpload { get; set; }
        public virtual DbSet<applicant> applicants { get; set; }
        public virtual DbSet<assignment_office> assignment_office { get; set; }
        public virtual DbSet<assignment_pwallet> assignment_pwallet { get; set; }
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<cert_info> cert_info { get; set; }
        //public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<g_agent_info> g_agent_info { get; set; }
        public virtual DbSet<g_app_info> g_app_info { get; set; }
        public virtual DbSet<g_applicant_info> g_applicant_info { get; set; }
        public virtual DbSet<g_ass_info> g_ass_info { get; set; }
        public virtual DbSet<g_cert_info> g_cert_info { get; set; }
        public virtual DbSet<g_change_info> g_change_info { get; set; }
        public virtual DbSet<g_merger_info> g_merger_info { get; set; }
        public virtual DbSet<g_other_items_info> g_other_items_info { get; set; }
        public virtual DbSet<g_prelim_search_info> g_prelim_search_info { get; set; }
        public virtual DbSet<g_pwallet> g_pwallet { get; set; }
        public virtual DbSet<g_renewal_info> g_renewal_info { get; set; }
        public virtual DbSet<g_tm_info> g_tm_info { get; set; }
        public virtual DbSet<g_tm_office> g_tm_office { get; set; }
        //public virtual DbSet<lga> lgas { get; set; }
        public virtual DbSet<logo_description> logo_description { get; set; }
        public virtual DbSet<mark_info> mark_info { get; set; }
        public virtual DbSet<mark_infoAmendment> mark_infoAmendment { get; set; }
        public virtual DbSet<namechange> namechanges { get; set; }
        public virtual DbSet<namechange_office> namechange_office { get; set; }
        public virtual DbSet<namechange_pwallet> namechange_pwallet { get; set; }
        public virtual DbSet<national_classes> national_classes { get; set; }
        public virtual DbSet<pwallet> pwallets { get; set; }
        public virtual DbSet<pwalletAmendment> pwalletAmendments { get; set; }
        public virtual DbSet<Recordal> Recordals { get; set; }
        public virtual DbSet<Recordal2> Recordal2 { get; set; }
        public virtual DbSet<Recordal3> Recordal3 { get; set; }
        public virtual DbSet<renewal> renewals { get; set; }
        public virtual DbSet<renewal_office> renewal_office { get; set; }
        public virtual DbSet<renewal_pwallet> renewal_pwallet { get; set; }
        public virtual DbSet<representative> representatives { get; set; }
        //public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<search_wallet> search_wallet { get; set; }
        public virtual DbSet<search_wallet2> search_wallet2 { get; set; }
        //public virtual DbSet<state> states { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tm_office> tm_office { get; set; }
        public virtual DbSet<tm_type> tm_type { get; set; }
        public virtual DbSet<xadminz_tm> xadminz_tm { get; set; }
        public virtual DbSet<xtransaction> xtransactions { get; set; }
        public virtual DbSet<address2> address2 { get; set; }
        public virtual DbSet<address4> address4 { get; set; }
        public virtual DbSet<mark_info2> mark_info2 { get; set; }
        public virtual DbSet<pwallet2> pwallet2 { get; set; }
        public virtual DbSet<pwallet3> pwallet3 { get; set; }
        public virtual DbSet<pwallet4> pwallet4 { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<tm_office2> tm_office2 { get; set; }
        public virtual DbSet<tm_printed_office> tm_printed_office { get; set; }
    
        public virtual int sp_a_address(string countryID, string stateID, string lgaID, string city, string street, string zip, string telephone1, string telephone2, string email1, string email2, string log_staff, string reg_date, Nullable<bool> visible)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("countryID", countryID) :
                new ObjectParameter("countryID", typeof(string));
    
            var stateIDParameter = stateID != null ?
                new ObjectParameter("stateID", stateID) :
                new ObjectParameter("stateID", typeof(string));
    
            var lgaIDParameter = lgaID != null ?
                new ObjectParameter("lgaID", lgaID) :
                new ObjectParameter("lgaID", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var telephone1Parameter = telephone1 != null ?
                new ObjectParameter("telephone1", telephone1) :
                new ObjectParameter("telephone1", typeof(string));
    
            var telephone2Parameter = telephone2 != null ?
                new ObjectParameter("telephone2", telephone2) :
                new ObjectParameter("telephone2", typeof(string));
    
            var email1Parameter = email1 != null ?
                new ObjectParameter("email1", email1) :
                new ObjectParameter("email1", typeof(string));
    
            var email2Parameter = email2 != null ?
                new ObjectParameter("email2", email2) :
                new ObjectParameter("email2", typeof(string));
    
            var log_staffParameter = log_staff != null ?
                new ObjectParameter("log_staff", log_staff) :
                new ObjectParameter("log_staff", typeof(string));
    
            var reg_dateParameter = reg_date != null ?
                new ObjectParameter("reg_date", reg_date) :
                new ObjectParameter("reg_date", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("visible", visible) :
                new ObjectParameter("visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_address", countryIDParameter, stateIDParameter, lgaIDParameter, cityParameter, streetParameter, zipParameter, telephone1Parameter, telephone2Parameter, email1Parameter, email2Parameter, log_staffParameter, reg_dateParameter, visibleParameter);
        }
    
        public virtual int sp_a_address_service(string countryID, string stateID, string lgaID, string city, string street, string zip, string telephone1, string telephone2, string email1, string email2, string log_staff, string reg_date, Nullable<bool> visible)
        {
            var countryIDParameter = countryID != null ?
                new ObjectParameter("countryID", countryID) :
                new ObjectParameter("countryID", typeof(string));
    
            var stateIDParameter = stateID != null ?
                new ObjectParameter("stateID", stateID) :
                new ObjectParameter("stateID", typeof(string));
    
            var lgaIDParameter = lgaID != null ?
                new ObjectParameter("lgaID", lgaID) :
                new ObjectParameter("lgaID", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var telephone1Parameter = telephone1 != null ?
                new ObjectParameter("telephone1", telephone1) :
                new ObjectParameter("telephone1", typeof(string));
    
            var telephone2Parameter = telephone2 != null ?
                new ObjectParameter("telephone2", telephone2) :
                new ObjectParameter("telephone2", typeof(string));
    
            var email1Parameter = email1 != null ?
                new ObjectParameter("email1", email1) :
                new ObjectParameter("email1", typeof(string));
    
            var email2Parameter = email2 != null ?
                new ObjectParameter("email2", email2) :
                new ObjectParameter("email2", typeof(string));
    
            var log_staffParameter = log_staff != null ?
                new ObjectParameter("log_staff", log_staff) :
                new ObjectParameter("log_staff", typeof(string));
    
            var reg_dateParameter = reg_date != null ?
                new ObjectParameter("reg_date", reg_date) :
                new ObjectParameter("reg_date", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("visible", visible) :
                new ObjectParameter("visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_address_service", countryIDParameter, stateIDParameter, lgaIDParameter, cityParameter, streetParameter, zipParameter, telephone1Parameter, telephone2Parameter, email1Parameter, email2Parameter, log_staffParameter, reg_dateParameter, visibleParameter);
        }
    
        public virtual int sp_a_applicant(string name, string type, string tax_id_type, string tax_id_number, string individual_id_number, string nationality, string addressID, string log_staff, string reg_date, Nullable<bool> visible)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var tax_id_typeParameter = tax_id_type != null ?
                new ObjectParameter("tax_id_type", tax_id_type) :
                new ObjectParameter("tax_id_type", typeof(string));
    
            var tax_id_numberParameter = tax_id_number != null ?
                new ObjectParameter("tax_id_number", tax_id_number) :
                new ObjectParameter("tax_id_number", typeof(string));
    
            var individual_id_numberParameter = individual_id_number != null ?
                new ObjectParameter("individual_id_number", individual_id_number) :
                new ObjectParameter("individual_id_number", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("nationality", nationality) :
                new ObjectParameter("nationality", typeof(string));
    
            var addressIDParameter = addressID != null ?
                new ObjectParameter("addressID", addressID) :
                new ObjectParameter("addressID", typeof(string));
    
            var log_staffParameter = log_staff != null ?
                new ObjectParameter("log_staff", log_staff) :
                new ObjectParameter("log_staff", typeof(string));
    
            var reg_dateParameter = reg_date != null ?
                new ObjectParameter("reg_date", reg_date) :
                new ObjectParameter("reg_date", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("visible", visible) :
                new ObjectParameter("visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_applicant", nameParameter, typeParameter, tax_id_typeParameter, tax_id_numberParameter, individual_id_numberParameter, nationalityParameter, addressIDParameter, log_staffParameter, reg_dateParameter, visibleParameter);
        }
    
        public virtual int sp_a_pwallet(string validationID, string stage, string reg_date, string applicantID, string data_status, string amt, Nullable<bool> visible)
        {
            var validationIDParameter = validationID != null ?
                new ObjectParameter("validationID", validationID) :
                new ObjectParameter("validationID", typeof(string));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var reg_dateParameter = reg_date != null ?
                new ObjectParameter("reg_date", reg_date) :
                new ObjectParameter("reg_date", typeof(string));
    
            var applicantIDParameter = applicantID != null ?
                new ObjectParameter("applicantID", applicantID) :
                new ObjectParameter("applicantID", typeof(string));
    
            var data_statusParameter = data_status != null ?
                new ObjectParameter("data_status", data_status) :
                new ObjectParameter("data_status", typeof(string));
    
            var amtParameter = amt != null ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("visible", visible) :
                new ObjectParameter("visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_pwallet", validationIDParameter, stageParameter, reg_dateParameter, applicantIDParameter, data_statusParameter, amtParameter, visibleParameter);
        }
    
        public virtual int sp_a_representative(string agent_code, string xname, string individual_id_type, string individual_id_number, string nationality, string addressID, string log_staff, string reg_date, Nullable<bool> visible)
        {
            var agent_codeParameter = agent_code != null ?
                new ObjectParameter("agent_code", agent_code) :
                new ObjectParameter("agent_code", typeof(string));
    
            var xnameParameter = xname != null ?
                new ObjectParameter("xname", xname) :
                new ObjectParameter("xname", typeof(string));
    
            var individual_id_typeParameter = individual_id_type != null ?
                new ObjectParameter("individual_id_type", individual_id_type) :
                new ObjectParameter("individual_id_type", typeof(string));
    
            var individual_id_numberParameter = individual_id_number != null ?
                new ObjectParameter("individual_id_number", individual_id_number) :
                new ObjectParameter("individual_id_number", typeof(string));
    
            var nationalityParameter = nationality != null ?
                new ObjectParameter("nationality", nationality) :
                new ObjectParameter("nationality", typeof(string));
    
            var addressIDParameter = addressID != null ?
                new ObjectParameter("addressID", addressID) :
                new ObjectParameter("addressID", typeof(string));
    
            var log_staffParameter = log_staff != null ?
                new ObjectParameter("log_staff", log_staff) :
                new ObjectParameter("log_staff", typeof(string));
    
            var reg_dateParameter = reg_date != null ?
                new ObjectParameter("reg_date", reg_date) :
                new ObjectParameter("reg_date", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("visible", visible) :
                new ObjectParameter("visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_representative", agent_codeParameter, xnameParameter, individual_id_typeParameter, individual_id_numberParameter, nationalityParameter, addressIDParameter, log_staffParameter, reg_dateParameter, visibleParameter);
        }
    
        public virtual int sp_a_tm_office(string pwalletID, string admin_status, string data_status, string xcomment, string xdoc1, string xdoc2, string xdoc3, string xofficer, string reg_date, Nullable<bool> xvisible)
        {
            var pwalletIDParameter = pwalletID != null ?
                new ObjectParameter("pwalletID", pwalletID) :
                new ObjectParameter("pwalletID", typeof(string));
    
            var admin_statusParameter = admin_status != null ?
                new ObjectParameter("admin_status", admin_status) :
                new ObjectParameter("admin_status", typeof(string));
    
            var data_statusParameter = data_status != null ?
                new ObjectParameter("data_status", data_status) :
                new ObjectParameter("data_status", typeof(string));
    
            var xcommentParameter = xcomment != null ?
                new ObjectParameter("xcomment", xcomment) :
                new ObjectParameter("xcomment", typeof(string));
    
            var xdoc1Parameter = xdoc1 != null ?
                new ObjectParameter("xdoc1", xdoc1) :
                new ObjectParameter("xdoc1", typeof(string));
    
            var xdoc2Parameter = xdoc2 != null ?
                new ObjectParameter("xdoc2", xdoc2) :
                new ObjectParameter("xdoc2", typeof(string));
    
            var xdoc3Parameter = xdoc3 != null ?
                new ObjectParameter("xdoc3", xdoc3) :
                new ObjectParameter("xdoc3", typeof(string));
    
            var xofficerParameter = xofficer != null ?
                new ObjectParameter("xofficer", xofficer) :
                new ObjectParameter("xofficer", typeof(string));
    
            var reg_dateParameter = reg_date != null ?
                new ObjectParameter("reg_date", reg_date) :
                new ObjectParameter("reg_date", typeof(string));
    
            var xvisibleParameter = xvisible.HasValue ?
                new ObjectParameter("xvisible", xvisible) :
                new ObjectParameter("xvisible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_tm_office", pwalletIDParameter, admin_statusParameter, data_statusParameter, xcommentParameter, xdoc1Parameter, xdoc2Parameter, xdoc3Parameter, xofficerParameter, reg_dateParameter, xvisibleParameter);
        }
    
        public virtual int sp_a_TmRegAdmin(string xroleID, string xname, string xemail, string xpass, string xtelephone1, string xtelephone2, string xsection, string xlog_officer, string xreg_date, Nullable<bool> xvisible)
        {
            var xroleIDParameter = xroleID != null ?
                new ObjectParameter("xroleID", xroleID) :
                new ObjectParameter("xroleID", typeof(string));
    
            var xnameParameter = xname != null ?
                new ObjectParameter("xname", xname) :
                new ObjectParameter("xname", typeof(string));
    
            var xemailParameter = xemail != null ?
                new ObjectParameter("xemail", xemail) :
                new ObjectParameter("xemail", typeof(string));
    
            var xpassParameter = xpass != null ?
                new ObjectParameter("xpass", xpass) :
                new ObjectParameter("xpass", typeof(string));
    
            var xtelephone1Parameter = xtelephone1 != null ?
                new ObjectParameter("xtelephone1", xtelephone1) :
                new ObjectParameter("xtelephone1", typeof(string));
    
            var xtelephone2Parameter = xtelephone2 != null ?
                new ObjectParameter("xtelephone2", xtelephone2) :
                new ObjectParameter("xtelephone2", typeof(string));
    
            var xsectionParameter = xsection != null ?
                new ObjectParameter("xsection", xsection) :
                new ObjectParameter("xsection", typeof(string));
    
            var xlog_officerParameter = xlog_officer != null ?
                new ObjectParameter("xlog_officer", xlog_officer) :
                new ObjectParameter("xlog_officer", typeof(string));
    
            var xreg_dateParameter = xreg_date != null ?
                new ObjectParameter("xreg_date", xreg_date) :
                new ObjectParameter("xreg_date", typeof(string));
    
            var xvisibleParameter = xvisible.HasValue ?
                new ObjectParameter("xvisible", xvisible) :
                new ObjectParameter("xvisible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_a_TmRegAdmin", xroleIDParameter, xnameParameter, xemailParameter, xpassParameter, xtelephone1Parameter, xtelephone2Parameter, xsectionParameter, xlog_officerParameter, xreg_dateParameter, xvisibleParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_s_IsValid(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_s_IsValid", idParameter);
        }
    
        public virtual int sp_u_MarkInfoRegNumber(string reg_number, string iD)
        {
            var reg_numberParameter = reg_number != null ?
                new ObjectParameter("reg_number", reg_number) :
                new ObjectParameter("reg_number", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_MarkInfoRegNumber", reg_numberParameter, iDParameter);
        }
    
        public virtual int sp_u_MarkInfoWithDocz(string logo_pic, string auth_doc, string sup_doc1, string sup_doc2, string iD)
        {
            var logo_picParameter = logo_pic != null ?
                new ObjectParameter("logo_pic", logo_pic) :
                new ObjectParameter("logo_pic", typeof(string));
    
            var auth_docParameter = auth_doc != null ?
                new ObjectParameter("auth_doc", auth_doc) :
                new ObjectParameter("auth_doc", typeof(string));
    
            var sup_doc1Parameter = sup_doc1 != null ?
                new ObjectParameter("sup_doc1", sup_doc1) :
                new ObjectParameter("sup_doc1", typeof(string));
    
            var sup_doc2Parameter = sup_doc2 != null ?
                new ObjectParameter("sup_doc2", sup_doc2) :
                new ObjectParameter("sup_doc2", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_MarkInfoWithDocz", logo_picParameter, auth_docParameter, sup_doc1Parameter, sup_doc2Parameter, iDParameter);
        }
    
        public virtual int sp_u_pwallet(string stage, string validationID)
        {
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var validationIDParameter = validationID != null ?
                new ObjectParameter("validationID", validationID) :
                new ObjectParameter("validationID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_pwallet", stageParameter, validationIDParameter);
        }
    
        public virtual int sp_u_PwalletAccPrintStatus(string iD, string acc_p)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var acc_pParameter = acc_p != null ?
                new ObjectParameter("acc_p", acc_p) :
                new ObjectParameter("acc_p", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_PwalletAccPrintStatus", iDParameter, acc_pParameter);
        }
    
        public virtual int sp_u_PwalletRtmStatus(string status, string iD, string data_status, string rtm)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var data_statusParameter = data_status != null ?
                new ObjectParameter("data_status", data_status) :
                new ObjectParameter("data_status", typeof(string));
    
            var rtmParameter = rtm != null ?
                new ObjectParameter("rtm", rtm) :
                new ObjectParameter("rtm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_PwalletRtmStatus", statusParameter, iDParameter, data_statusParameter, rtmParameter);
        }
    
        public virtual int sp_u_PwalletStage(string id, string applicantID, string amt, string stage, string data_status)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var applicantIDParameter = applicantID != null ?
                new ObjectParameter("applicantID", applicantID) :
                new ObjectParameter("applicantID", typeof(string));
    
            var amtParameter = amt != null ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(string));
    
            var stageParameter = stage != null ?
                new ObjectParameter("stage", stage) :
                new ObjectParameter("stage", typeof(string));
    
            var data_statusParameter = data_status != null ?
                new ObjectParameter("data_status", data_status) :
                new ObjectParameter("data_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_PwalletStage", idParameter, applicantIDParameter, amtParameter, stageParameter, data_statusParameter);
        }
    
        public virtual int sp_u_PwalletStatus(string status, string iD, string data_status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var data_statusParameter = data_status != null ?
                new ObjectParameter("data_status", data_status) :
                new ObjectParameter("data_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_PwalletStatus", statusParameter, iDParameter, data_statusParameter);
        }
    
        public virtual int sp_u_xadminz_pass(string xpass, string pwalletID)
        {
            var xpassParameter = xpass != null ?
                new ObjectParameter("xpass", xpass) :
                new ObjectParameter("xpass", typeof(string));
    
            var pwalletIDParameter = pwalletID != null ?
                new ObjectParameter("pwalletID", pwalletID) :
                new ObjectParameter("pwalletID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_u_xadminz_pass", xpassParameter, pwalletIDParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
