//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_agent_info
    {
        public long xid { get; set; }
        public string code { get; set; }
        public string xname { get; set; }
        public string xpassword { get; set; }
        public string nationality { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string log_staff { get; set; }
        public string xsync { get; set; }
    }
}
