//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_app_info
    {
        public long ID { get; set; }
        public string rtm_number { get; set; }
        public string application_no { get; set; }
        public string filing_date { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
        public string item_code { get; set; }
        public string reg_no { get; set; }
    }
}
