//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_applicant_info
    {
        public long ID { get; set; }
        public string xname { get; set; }
        public string address { get; set; }
        public string xemail { get; set; }
        public string xmobile { get; set; }
        public string nationality { get; set; }
        public string trading_as { get; set; }
        public string log_staff { get; set; }
        public string visible { get; set; }
    }
}
