//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_ass_info
    {
        public long xID { get; set; }
        public string date_of_assignment { get; set; }
        public string assignee_name { get; set; }
        public string assignee_address { get; set; }
        public string assignee_nationality { get; set; }
        public string assignor_name { get; set; }
        public string assignor_address { get; set; }
        public string assignor_nationality { get; set; }
        public string ass_doc { get; set; }
        public string log_staff { get; set; }
        public string xvisible { get; set; }
    }
}
