//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_change_info
    {
        public long xID { get; set; }
        public string old_name { get; set; }
        public string old_address { get; set; }
        public string old_goods { get; set; }
        public string old_tm_class { get; set; }
        public string new_name { get; set; }
        public string new_address { get; set; }
        public string new_goods { get; set; }
        public string new_tm_class { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
    }
}
