//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_merger_info
    {
        public long ID { get; set; }
        public string original_name { get; set; }
        public string original_address { get; set; }
        public string merging_name { get; set; }
        public string merging_address { get; set; }
        public string merged_coy_name { get; set; }
        public string merger_date { get; set; }
        public string merger_doc { get; set; }
        public string log_staff { get; set; }
        public string visible { get; set; }
    }
}
