//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_tm_info
    {
        public long xID { get; set; }
        public string reg_number { get; set; }
        public string xtype { get; set; }
        public string tm_title { get; set; }
        public string tm_class { get; set; }
        public string tm_desc { get; set; }
        public string logo_descID { get; set; }
        public string disclaimer { get; set; }
        public string logo_pic { get; set; }
        public string auth_doc { get; set; }
        public string sup_doc1 { get; set; }
        public string app_letter_doc { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
    }
}
