//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark_info
    {
        public long xID { get; set; }
        public string reg_number { get; set; }
        public string tm_typeID { get; set; }
        public string logo_descriptionID { get; set; }
        public string national_classID { get; set; }
        public string product_title { get; set; }
        public string nice_class { get; set; }
        public string nice_class_desc { get; set; }
        public string sign_type { get; set; }
        public string vienna_class { get; set; }
        public string disclaimer { get; set; }
        public string logo_pic { get; set; }
        public string auth_doc { get; set; }
        public string sup_doc1 { get; set; }
        public string sup_doc2 { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string xvisible { get; set; }
        public string xtime { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
    }
}
