//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class namechange
    {
        public long xID { get; set; }
        public string applicant_name { get; set; }
        public string applicant_address { get; set; }
        public string file_number { get; set; }
        public string certificate_number { get; set; }
        public string nice_class { get; set; }
        public string nice_class_desc { get; set; }
        public string old_name { get; set; }
        public string old_name_addy { get; set; }
        public string new_name { get; set; }
        public string new_name_addy { get; set; }
        public string change_date { get; set; }
        public string agent_name { get; set; }
        public string agent_code { get; set; }
        public string agent_mail { get; set; }
        public string namechange_pwalletID { get; set; }
        public string power_of_attorney { get; set; }
        public string regdate { get; set; }
        public string visible { get; set; }
    }
}
