//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordal
    {
        public int ID { get; set; }
        public string OLD_APPLICANTNAME { get; set; }
        public string NEW_APPLICANTNAME { get; set; }
        public Nullable<System.DateTime> RECORDAL_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> RECORDAL_APPROVE_DATE { get; set; }
        public string LOG_STAFF { get; set; }
        public string STATUS { get; set; }
        public string AMOUNT { get; set; }
        public string TRANSACTIONID { get; set; }
        public string RECORDAL_TYPE { get; set; }
        public string XOFFICER { get; set; }
        public string OLD_APPLICANTADDRESS { get; set; }
        public string NEW_APPLICANTADDRESS { get; set; }
        public string Xcomment { get; set; }
        public string OLD_AGENTNAME { get; set; }
        public string NEW_AGENTNAME { get; set; }
        public string OLD_AGENTCODE { get; set; }
        public string NEW_AGENTCODE { get; set; }
        public string OLD_AGENTEMAIL { get; set; }
        public string NEW_AGENTEMAIL { get; set; }
        public string OLD_AGENTPHONE { get; set; }
        public string NEW_AGENTPHONE { get; set; }
        public string OLD_PRODUCT_TITLE { get; set; }
        public string NEW_PRODUCT_TITLE { get; set; }
        public string OLD_PRODUCT_LOGO { get; set; }
        public string NEW_PRODUCT_LOGO { get; set; }
        public string LOGO_DESC { get; set; }
        public string Detail_Id { get; set; }
        public string data_status { get; set; }
        public string data_status2 { get; set; }
        public string data_status3 { get; set; }
        public string data_status4 { get; set; }
        public string Description { get; set; }
        public string OLDAGENT_ADDRESS { get; set; }
        public string NEWAGENT_ADDRESS { get; set; }
        public string UPLOADPATH { get; set; }
    }
}
