//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordal3
    {
        public int Id { get; set; }
        public string Renewal_DueDate { get; set; }
        public string Renewal_Type { get; set; }
        public string power_of_attorney { get; set; }
        public string Certificate_Of_Registration { get; set; }
        public string Applicant_name { get; set; }
        public string Applicant_Address { get; set; }
        public string Reg_Date { get; set; }
    }
}
