//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordal2
    {
        public int Id { get; set; }
        public string oldApplicantName { get; set; }
        public string newApplicantName { get; set; }
        public string newApplicantAddress { get; set; }
        public string oldApplicantAddress { get; set; }
        public string newApplicantNationality { get; set; }
        public string OldApplicantNationality { get; set; }
        public string newApplicantDescription { get; set; }
        public string status { get; set; }
        public string status2 { get; set; }
        public string assignment_upload { get; set; }
        public string Assignee_upload { get; set; }
        public string deed_Assignment_upload { get; set; }
        public string Power_of_Attorney_upload { get; set; }
        public string Registration_of_Mark_upload { get; set; }
        public string Assignment_Date { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Registrar_direction { get; set; }
        public string advertisements_complying { get; set; }
        public string publication { get; set; }
        public string name_certificate { get; set; }
    }
}
