//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class renewal_pwallet
    {
        public long ID { get; set; }
        public string validationID { get; set; }
        public string amt { get; set; }
        public string stage { get; set; }
        public string status { get; set; }
        public string data_status { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
    }
}
