//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class representative
    {
        public long ID { get; set; }
        public string agent_code { get; set; }
        public string xname { get; set; }
        public string individual_id_type { get; set; }
        public string individual_id_number { get; set; }
        public string nationality { get; set; }
        public string addressID { get; set; }
        public string log_staff { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
        public string xtime { get; set; }
    }
}
