//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class search_wallet2
    {
        public long ID { get; set; }
        public string mark_infoID { get; set; }
        public string search_str { get; set; }
        public string search_cri { get; set; }
        public string xclass { get; set; }
        public string log_officer { get; set; }
        public string reg_date { get; set; }
        public string visible { get; set; }
    }
}
