//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_printed_office
    {
        public long ID { get; set; }
        public string pwalletID { get; set; }
        public string admin_status { get; set; }
        public string data_status { get; set; }
        public string xcomment { get; set; }
        public string xdoc1 { get; set; }
        public string xdoc2 { get; set; }
        public string xdoc3 { get; set; }
        public string xofficer { get; set; }
        public string reg_date { get; set; }
        public Nullable<bool> xvisible { get; set; }
        public string xtime { get; set; }
    }
}
