//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class xadminz_tm
    {
        public long xID { get; set; }
        public string xroleID { get; set; }
        public string xname { get; set; }
        public string xemail { get; set; }
        public string xpass { get; set; }
        public string xtelephone1 { get; set; }
        public string xtelephone2 { get; set; }
        public string xsection { get; set; }
        public string xlog_officer { get; set; }
        public string xreg_date { get; set; }
        public string xvisible { get; set; }
    }
}
