//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.model7
{
    using System;
    using System.Collections.Generic;
    
    public partial class xtransaction
    {
        public long ID { get; set; }
        public string transactionID { get; set; }
        public string xcode { get; set; }
        public string ptype { get; set; }
        public string amt { get; set; }
        public string status { get; set; }
        public string adminID { get; set; }
    }
}
